# Generated by Django 4.0.6 on 2022-09-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_lat_alter_place_lng'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('title', 'lat', 'lng'), name='unique_place'),
        ),
    ]
