# Generated by Django 4.0.6 on 2022-09-08 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_place_unique_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(-90), django.core.validators.MinValueValidator(90)], verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(-180), django.core.validators.MinValueValidator(180)], verbose_name='Долгота'),
        ),
    ]
